name: Open pull request to main
on:
  pull_request:
    branches:
      - main
jobs:
  pr-check:
    name: Main pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: make install-ci
      - name: Eslint check
        run: make eslint-check
      - name: Prettier check
        run: make prettier-check
      - name: Typescript check
        run: make ts-check
      - name: Run tests
        env:
          MAINNET_URL: ${{ secrets.MAINNET_URL }}
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
        run: make test 