name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: make install-ci
      - name: Eslint check
        run: make eslint-check
      - name: Prettier check
        run: make prettier-check
      - name: Typescript check
        run: make ts-check
      - name: Run tests
        env:
          MAINNET_URL: ${{ secrets.MAINNET_URL }}
          COINGECKO_API_KEY: ${{ secrets.COINGECKO_API_KEY }}
        run: make test
      - name: Build release
        run: make build-release
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PUBLISHING_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISHING_TOKEN }}
        run: make release
